SELECT
    *
FROM
    PROCDB_B_P01_LAK.L_MR_000.VW_HMD_ANCL_DPOINTCLUB_ATTRIBUTE_ENQUETE_MASTER
WHERE
    CATEGORY_NUMBER = '質問'
    AND TITLE RLIKE '.*個人年収.*'
    AND IMPLEMENTATION_SEASON = '2026-04-01';