SELECT
    *
FROM
    PROCDB_B_P01_LAK.L_MR_000.VW_HMD_ANCL_DPOINTCLUB_ATTRIBUTE_ENQUETE_MASTER
WHERE
    CATEGORY_NUMBER = '回答'
    AND TITLE RLIKE '.*推定業種.*'
    AND IMPLEMENTATION_SEASON = '2026-03-01';